name: moment
description: 记录美好瞬间

# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+22

environment:
  sdk: '>=2.2.2 <3.0.0'
  flutter: '>=1.12.13+hotfix.5'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  dio: ^3.0.4
  flutter_easyrefresh: ^2.0.4
  flutter_swiper: ^1.1.6
  sqflite: ^1.1.7+3
  #  flutter_markdown: ^0.3.0
  fluttertoast: ^3.1.3
  #  flutter_calendar: 0.0.8
  provider: ^3.2.0
  shared_preferences: ^0.5.4+8
  path_provider: ^1.4.5
  archive: ^2.0.11
  permission_handler: ^4.0.0
  file_picker: ^1.4.2
  photo_view: ^0.9.0
  url_launcher: ^5.2.7
  event_bus: ^1.1.0
  package_info: ^0.4.0+12
  share_extend: ^1.1.0
  fl_chart: ^0.4.2
  flutter_cupertino_date_picker: ^1.0.12
  flutter_keyboard_visibility: ^0.7.0
  cuberto_bottom_bar: ^1.0.0
  # add_2_calendar: ^1.3.1
  # android_intent: ^0.3.4+7
  flutter_colorpicker: ^0.2.6
  # flutter_staggered_animations: ^0.1.2
  #flutter_sound: ^1.5.2
#  multi_image_picker: ^4.6.0

  # for webdav
  retry: ^2.0.0
  xml: ^3.5.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# following page: https://dart.dev/tools/pub/pubspec
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/asserts/images/
    - lib/asserts/logo/logo.png
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # https://flutter.dev/assets-and-images/#from-packages
  # see https://flutter.dev/custom-fonts/#from-packages
