name: moment
description: 记录美好瞬间

# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+29

environment:
  sdk: '>=2.2.2 <3.0.0'
  flutter: '>=1.12.13+hotfix.5'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  dio: ^4.0.1
  #  flutter_easyrefresh: ^2.0.4
  # flutter_swiper: ^1.1.6
  card_swiper: ^1.0.4
  sqflite: ^2.0.0+4
  #  flutter_markdown: ^0.3.0
  fluttertoast: ^8.0.8
  #  flutter_calendar: 0.0.8
  provider: ^6.0.1
  shared_preferences: ^2.0.8
  path_provider: ^2.0.6
  archive: ^3.1.6
  permission_handler: ^8.2.5
  file_picker: ^4.2.0
  photo_view: ^0.13.0
  url_launcher: ^6.0.12
  event_bus: ^2.0.0
  package_info: ^2.0.2
  share_extend: ^2.0.0
  fl_chart: ^0.40.2
  # flutter_cupertino_date_picker: ^1.0.12
  flutter_cupertino_datetime_picker: ^3.0.0
  flutter_keyboard_visibility: ^5.1.0
  # cuberto_bottom_bar: ^1.0.0
  # add_2_calendar: ^1.3.1
  # android_intent: ^0.3.4+7
  flutter_colorpicker: ^0.6.0
  # flutter_staggered_animations: ^0.1.2
  #flutter_sound: ^1.5.2
  #  multi_image_picker: ^4.6.0
  # flutter_webview_plugin: ^0.3.10
  flutter_markdown: ^0.6.8

  # for webdav
  retry: ^3.1.0
  xml: ^5.3.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# following page: https://dart.dev/tools/pub/pubspec
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/asserts/logo/logo.png
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # https://flutter.dev/assets-and-images/#from-packages
  # see https://flutter.dev/custom-fonts/#from-packages
